sudo: required

language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - kcov

after_success: |
  kcov --help &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/cov target/debug/kg-utils-*