language: rust
rust:
  - nightly

after_success:
  - sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev libiberty-dev zlib1g-dev cmake gcc binutils-dev
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - cd kcov-master
  - mkdir build
  - cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../..
  - rm -rf kcov-master
  - kcov --coveralls-id=$TRAVIS_JOB_ID --verify --exclude-pattern=/.cargo,/usr/lib target/cov target/debug/kg_utils-*
