sudo: required

language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - kcov

script:
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/cov target/debug/kg-utils-*
