sudo: required

language: rust
rust:
  - nightly

services:
  - docker

cache:
  directories:
    - target/debug/deps
    - targe/debug/build

addons:
  apt:
    packages:
      - kcov

after_success: |
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/cov target/debug/kg-utils-*