sudo: required

language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - kcov

after_success:
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo,/usr/lib target/cov target/debug/kg_utils-*
