sudo: required

language: rust
rust:
  - nightly

addons:
  apt:
    packages:
      - kcov

after_success:
  - ls -la target/cov
  - ls -la target/debug
  - kcov ./target/cov ./target/debug/kg-utils-*
